version: '3.3'
services:
       api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db
          
    db:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=AVeryComplex(!)123Password
        ports:
            - '6126:1433'
        image: mcr.microsoft.com/mssql/server:2022-latest



